### ISSUE TITLE
Jupyter user survey

### ISSUE THREAD

**Issue by willingc** [jupyter/datasets#2]
@parente It might be nice to link from here to the work that you did on the Jupyter user survey.

**Comment by parente** [comment]
I was thinking it might even be better to port that work here ...

**Comment by willingc** [comment]
@parente Have at it :smile:

**Comment by parente** [comment]
My only concern is the redirect. If it's gone over there, how do we leave a note saying "come here". Leave a README with a link?

**Comment by takluyver** [comment]
I think leaving a README with a link would be a satisfactory solution.

For other people reading this, the material this issue is about is currently [here](https://github.com/jupyter/design/tree/master/surveys/2015-notebook-ux). Linking because it took me a few minutes to find it ;-)

**Comment by parente** [comment]
Closed by #3.
